# Development profile configuration
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: order_worker_dev

  redis:
    host: localhost
    port: 6379

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    auto-offset-reset: earliest
    group-id: order-worker-dev

enricher-api:
  base-url: http://localhost:8080

# Enable debug logging for development
logging:
  level:
    com.resilient.orderworker: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.data.mongodb: DEBUG
    reactor.kafka: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Relaxed resilience settings for development
resilience4j:
  circuitbreaker:
    instances:
      customerService:
        failure-rate-threshold: 80
        wait-duration-in-open-state: 10s
      productService:
        failure-rate-threshold: 80
        wait-duration-in-open-state: 10s

  retry:
    instances:
      customerService:
        max-attempts: 2
        wait-duration: 500ms
      productService:
        max-attempts: 2
        wait-duration: 500ms
